languages: cpp

os: linux
dist: xenial
cache: ccache

matrix:
  include:
    - name: "GCC CUDA Debug (linux)"
      os: linux
      compiler: gcc
      env:
      - BUILD=Debug
    - name: "GCC OpenCL Debug (linux)"
      os: linux
      compiler: gcc
      env:
      - BUILD=Debug
    - name: "Clang Metal Debug (osx)"
      os: osx
      env:
      - BUILD=Debug
      addons:
        homebrew:
          packages:
            - cmake
          update: true

addons:
  apt:
    update: true
    source:
      # - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - clang-tidy
      - cppcheck


before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      export CMAKE_MAJOR_VERSION=3.17;
      export CMAKE_MINOR_VERSION=2;
      wget -q https://cmake.org/files/v${CMAKE_MAJOR_VERSION}/cmake-${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}-Linux-x86_64.sh && mkdir /opt/cmake && sh ./cmake-${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}-Linux-x86_64.sh --prefix=/opt/cmake --skip-license && sudo ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake && rm ./cmake-${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}-Linux-x86_64.sh && export PATH=/usr/local/bin:$PATH;
      git clone --depth 1 https://github.com/tmcdonell/travis-scripts.git;
      export CUDA=11.0.3;
      sudo ./travis-scripts/install-cuda-trusty.sh;
    fi;
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then
      choco upgrade cmake -y --version=3.17.2;
      choco install cuda -y --version=11.0.3;
    fi;

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD} ..
  - cmake --build .
    # Don't run the tests, just build it
